#' Checking helper functions
#'
#' These helper functions allowing easy checking over multiple columns and
#' filtering to subsets of the data:
#'   * `chk_filter` applies `func` with `args` to `var` in `data` filtered
#'     with `flt` and returns the resulting logical vector.
#'   * `chk_filter_vars` applies `func` with `args` to `vars` in `data`
#'     filtered with `flt` and returns a dataframe containing the resulting
#'     logical vectors.
#'   * `chk_filter_all` and `chk_filter_any` are wrappers around
#'     `chk_filter_vars` which return a single logical vector produced by
#'     taking the conjunction and disjunction, respectively, of the columns
#'     in the output of `chk_filter_vars`
#'   * `chk_filter_where` works exactly the same as `chk_filter_all` except that
#'     the variables are specified not using `dplyr::vars()` (`vars`) but using
#'     bare [`tidy-select`][dplyr_tidy_select] functions (`where`).
#'
#'
#' @param data a `tbl`
#' @param var a single column to check
#' @param vars a list of columns to check generated by [vars()][dplyr::vars()]
#' @param func a function to use use for checking. The provided function should
#'   take a single vector as input and return a logical vector.
#' @param flt a logical expression to be applied as a filter for the check. This
#'   will be evaluated in the context of data
#' @param args a list of additional arguments to be added to the function calls.
#' @return A logical vector flagging records that have passed or failed the
#'   check, with `NA` where records do not meet the filter
#' @examples
#'
#' # Check that every 4-cylinder car has an engine displacement of < 100 cubic
#' # inches
#' x <- chk_filter(mtcars, disp, chk_range, cyl == 4, list(min = 0, max = 100))
#' all(x, na.rm = TRUE)
#'
#' # Check that every 4-cylinder car has an engine displacement of < 100 cubic
#' # inches AND < 100 horsepower
#' chk_filter_all(
#'   mtcars,
#'   c("disp", "hp"),
#'   chk_range,
#'   cyl == 4,
#'   list(min = 0, max = 100)
#' )
#'
#' # Check that columns made up of whole numbers are binary
#' chk_filter_where(
#'   mtcars,
#'   where(~ all(. %% 1 == 0)),
#'   chk_values,
#'   TRUE,
#'   list(0:1)
#' )
#'
#' @seealso [Generic Checking Functions][chk-generic]
#' @name chk-helper
NULL

#' @rdname chk-helper
#' @export
chk_filter <- function(data, var, func, flt = TRUE, args = list()) {
  var <- enquo(var)
  flt <- enquo(flt)

  # data %>% mutate(.chk = if_else(!!flt, func(!!var), NA)) %>% pull(.chk)
  data %>%
    mutate(.cond = !!flt) %>%
    mutate_at(quos(!!var), func, !!!args) %>%
    mutate_at(quos(!!var), ~ifelse(.cond, ., NA)) %>%
    # select(!!!var)
    pull(!!var)
}

#' @rdname chk-helper
#' @export
chk_filter_vars <- function(data, vars, func, flt = TRUE, args = list()) {
  # vars <- enquo(vars)
  flt <- enquo(flt)

  flt <- data %>%
    transmute(.cond = !!flt)

  data %>%
    mutate_at(vars, func, !!!args) %>%
    select(!!!vars) %>%
    mutate_all(~ifelse(flt$.cond, ., NA))
}

#' @rdname chk-helper
#' @export
chk_filter_all <- function(data, vars, func, flt = TRUE, args = list()) {
  chk_filter_vars(data, vars, func, !!enquo(flt), args) %>%
    apply(1, all)
}

#' @rdname chk-helper
#' @export
chk_filter_any <- function(data, vars, func, flt = TRUE, args = list()) {
  chk_filter_vars(data, vars, func, !!enquo(flt), args) %>%
    apply(1, any)
}

#' @rdname chk-helper
#' @param where <[`tidy-select`][dplyr_tidy_select]> columns to check
#' @export
chk_filter_where <- function(data, where, func, flt = TRUE, args = list()) {
  flt <- enquo(flt)
  where <- enquo(where)

  data <- data %>%
    mutate(.cond = !!flt) %>%
    select(!!where, .data$.cond)

  data %>%
    mutate(across(-.data$.cond, func, !!!args)) %>%
    mutate(across(-.data$.cond, ~ifelse(.data$.cond, ., NA))) %>%
    select(-.data$.cond) %>%
    apply(1, all)
}
