#' Generic Checking Functions
#'
#' These functions provide common, simple data checks.
#'
#' @param x vector to check
#' @param miss vector of values to be treated as missing
#' @param len maximum string length for checking string variables
#' @param val value for equality check
#' @param min minimum value for range check
#' @param max maximum value for range check
#' @return A logical vector flagging records that have passed or failed the check
#' @seealso [Checking Helper Functions][check_helper]
#' @name check_generic
NULL

#' @rdname check_generic
#' @export
chk_dummy <- function(x) {
  x == x
}

#' @rdname check_generic
#' @export
chk_blank <- function(x) {
  x %in% c("", NA)
}

#' @rdname check_generic
#' @export
chk_equals <- function(x, val) {
  chk_blank(x) | x == val
}

#' @rdname check_generic
#' @export
chk_range <- function(x, min, max) {
  chk_blank(x) | (x >= min & x <= max)
}

#' @rdname check_generic
#' @export
chk_pattern <- function(x, pattern) {
  chk_blank(x) | str_detect(x, pattern)
}

#' @rdname check_generic
#' @export
chk_length <- function(x, len) {
  chk_blank(x) | str_length(x) <= len
}

#' @rdname check_generic
#' @export
chk_miss <- function(x, miss = getOption("testdat.miss_text")) {
  tolower(x) %in% miss
}

#' @rdname check_generic
#' @export
chk_nmiss <- function(x, miss = getOption("testdat.miss_text")) {
  !chk_miss(x, miss)
}

#' @rdname check_generic
#' @export
chk_unique <- function(x) {
  chk_blank(x) | !(duplicated(x, fromLast = T) | duplicated(x, fromLast = F))
}

#' @rdname check_generic
#' @export
chk_date_yyyymmdd <- function(x) {
  chk_blank(x) | (str_detect(x, "[0-9]{8}") & !is.na(lubridate::ymd(x, quiet = TRUE)))
}

#' @rdname check_generic
#' @export
chk_date_yyyymm <- function(x) {
  chk_blank(x) | (str_detect(x, "[0-9]{6}") & !is.na(lubridate::ymd(paste0(x, "01"), quiet = TRUE)))
}

#' @rdname check_generic
#' @export
chk_date_yyyy <- function(x) {
  chk_blank(x) | (str_detect(x, "[0-9]{4}") & !is.na(lubridate::ymd(paste0(x, "0101"), quiet = TRUE)))
}

#' @rdname check_generic
#' @export
chk_ascii <- function(x) {
  is.na(x) | !any(grepl("[^\x20-\x7E]", var))
}

#' @rdname check_generic
#' @export
chk_values <- function(x, ..., miss = TRUE) {
  x %in% c(unlist(list(...)),
           ifelse(miss, getOption("testdat.miss"), NULL))
}

#' Checking Helper Functions
#'
#' These helper functions allowing easy checking over multiple columns and filtering to subsets of the data.
#'
#' @param .dat a `tbl`
#' @param .vars a list of columns to check generated by [vars()][dplyr::vars()]
#' @param .func a function to use use for checking. The provided function should take a single vector as input and return a logical vector.
#' @param .flt a logical expression to be applied as a filter for the check. This will be evaluated in the context of .dat
#' @param .args a list of additional arguments to be added to the function calls.
#' @return A logical vector flagging records that have passed or failed the check, with `NA` where records do not meet the filter
#' @name check_helper
NULL

#' @rdname check_helper
#' @export
chk_filter <- function(.dat, .var, .func, .flt = TRUE, .args = list()) {
  .var <- enquo(.var)
  .flt <- enquo(.flt)

  # .dat %>% mutate(.chk = if_else(!!.flt, .func(!!.var), NA)) %>% pull(.chk)
  .dat %>%
    mutate(.cond = !!.flt) %>%
    mutate_at(quos(!!.var), funs(.func, .args = .args)) %>%
    mutate_at(quos(!!.var), funs(ifelse(.cond, ., NA))) %>%
    # select(!!!.var)
    pull(!!.var)
}

#' @rdname check_helper
#' @export
chk_filter_vars <- function(.dat, .vars, .func, .flt = TRUE, .args = list()) {
  # .vars <- enquo(.vars)
  .flt <- enquo(.flt)

  .dat %>%
    mutate(.cond = !!.flt) %>%
    mutate_at(.vars, funs(.func, .args = .args)) %>%
    mutate_at(.vars, funs(ifelse(.cond, ., NA))) %>%
    select(!!!.vars)
}

#' @rdname check_helper
#' @export
chk_filter_all <- function(.dat, .vars, .func, .flt = TRUE, .args = list()) {
  chk_filter_vars(.dat, .vars, .func, !!enquo(.flt), .args) %>%
    apply(1, all)
}

#' @rdname check_helper
#' @export
chk_filter_any <- function(.dat, .vars, .func, .flt = TRUE, .args = list()) {
  chk_filter_vars(.dat, .vars, .func, !!enquo(.flt), .args) %>%
    apply(1, any)
}

