#' Generic checking functions
#'
#' These functions provide common, simple data checks.
#'
#' @param x vector to check
#' @param miss vector of values to be treated as missing
#' @return A logical vector flagging records that have passed or failed the check
#' @seealso [Checking Helper Functions][chk-helper]
#' @name chk-generic
NULL

#' @rdname chk-generic
#' @export
chk_dummy <- function(x) {
  x == x
}

#' @rdname chk-generic
#' @export
chk_blank <- function(x) {
  x %in% c("", NA)
}

#' @rdname chk-generic
#' @param val value for equality check
#' @export
chk_equals <- function(x, val) {
  chk_blank(x) | x == val
}

#' @rdname chk-generic
#' @param min minimum value for range check
#' @param max maximum value for range check
#' @export
chk_range <- function(x, min, max) {
  chk_blank(x) | ifelse(suppressWarnings((as.numeric(x) >= min & as.numeric(x) <= max)) %in% NA, FALSE, suppressWarnings((as.numeric(x) >= min & as.numeric(x) <= max)))
}

#' @rdname chk-generic
#' @param pattern pattern to look for as defined in
#'   [str_detect()][stringr::str_detect()]
#' @importFrom stringr str_detect
#' @export
chk_pattern <- function(x, pattern) {
  x <- as_char_scipen(x)
  chk_blank(x) | str_detect(x, pattern)
}

#' @rdname chk-generic
#' @param len maximum string length for checking string variables
#' @importFrom stringr str_length
#' @export
chk_max_length <- function(x, len) {
  x <- as_char_scipen(x)
  chk_blank(x) | str_length(x) <= len
}

#' @rdname chk-generic
#' @export
chk_text_miss <- function(x, miss = getOption("testdat.miss_text")) {
  tolower(x) %in% miss
}

#' @rdname chk-generic
#' @export
chk_text_nmiss <- function(x, miss = getOption("testdat.miss_text")) {
  !chk_miss(x, miss)
}

#' @rdname chk-generic
#' @export
chk_unique <- function(x) {
  chk_blank(x) | !(duplicated(x, fromLast = T) | duplicated(x, fromLast = F))
}

#' @rdname chk-generic
#' @importFrom stringr str_detect
#' @importFrom lubridate ymd
#' @export
chk_date_yyyymmdd <- function(x) {
  chk_blank(x) | (str_detect(x, "[0-9]{8}") & !is.na(lubridate::ymd(x, quiet = TRUE)))
}

#' @rdname chk-generic
#' @importFrom stringr str_detect
#' @importFrom lubridate ymd
#' @export
chk_date_yyyymm <- function(x) {
  chk_blank(x) | (str_detect(x, "[0-9]{6}") & !is.na(lubridate::ymd(paste0(x, "01"), quiet = TRUE)))
}

#' @rdname chk-generic
#' @importFrom stringr str_detect
#' @importFrom lubridate ymd
#' @export
chk_date_yyyy <- function(x) {
  chk_blank(x) | (str_detect(x, "[0-9]{4}") & !is.na(lubridate::ymd(paste0(x, "0101"), quiet = TRUE)))
}

#' @rdname chk-generic
#' @export
chk_ascii <- function(x) {
  x <- as_char_scipen(x)
  chk_blank(x) | !any(grepl("[^\x20-\x7E]", x))
}

#' @rdname chk-generic
#' @param ... vectors of valid values
#' @export
chk_values <- function(x, ..., miss = getOption("testdat.miss")) {
  old <- options(scipen = getOption("testdat.scipen"))
  on.exit(options(old))
  x %in% c(unlist(list(...)), miss)
}

#' Checking helper functions
#'
#' These helper functions allowing easy checking over multiple columns and filtering to subsets of the data.
#'
#' @param .dat a `tbl`
#' @param .var a single column to check
#' @param .vars a list of columns to check generated by [vars()][dplyr::vars()]
#' @param .func a function to use use for checking. The provided function should take a single vector as input and return a logical vector.
#' @param .flt a logical expression to be applied as a filter for the check. This will be evaluated in the context of .dat
#' @param .args a list of additional arguments to be added to the function calls.
#' @return A logical vector flagging records that have passed or failed the check, with `NA` where records do not meet the filter
#' @seealso [Generic Checking Functions][chk-generic]
#' @name chk-helper
NULL

#' @rdname chk-helper
#' @export
chk_filter <- function(.dat, .var, .func, .flt = TRUE, .args = list()) {
  .var <- enquo(.var)
  .flt <- enquo(.flt)

  # .dat %>% mutate(.chk = if_else(!!.flt, .func(!!.var), NA)) %>% pull(.chk)
  .dat %>%
    mutate(.cond = !!.flt) %>%
    mutate_at(quos(!!.var), .func, !!!.args) %>%
    mutate_at(quos(!!.var), ~ifelse(.cond, ., NA)) %>%
    # select(!!!.var)
    pull(!!.var)
}

#' @rdname chk-helper
#' @export
chk_filter_vars <- function(.dat, .vars, .func, .flt = TRUE, .args = list()) {
  # .vars <- enquo(.vars)
  .flt <- enquo(.flt)

  .dat %>%
    mutate(.cond = !!.flt) %>%
    mutate_at(.vars, .func, !!!.args) %>%
    mutate_at(.vars, ~ifelse(.cond, ., NA)) %>%
    select(!!!.vars)
}

#' @rdname chk-helper
#' @export
chk_filter_all <- function(.dat, .vars, .func, .flt = TRUE, .args = list()) {
  chk_filter_vars(.dat, .vars, .func, !!enquo(.flt), .args) %>%
    apply(1, all)
}

#' @rdname chk-helper
#' @export
chk_filter_any <- function(.dat, .vars, .func, .flt = TRUE, .args = list()) {
  chk_filter_vars(.dat, .vars, .func, !!enquo(.flt), .args) %>%
    apply(1, any)
}

