#' @importFrom glue glue
NULL

#' Expectation params
#' @keywords internal
#' @param var an unquoted variable name
#' @param vars a list of columns generated by [vars()]
#' @param flt a filter specifying a subset of the dataset to test
#' @param miss a vector of values to be treated as missing. The
#'   [testdat.miss][testdat] option is used by default
#' @param data data frame to test. The [global test data][global-data] is used
#'   by default.
#' @export vars
#' @name data-params
NULL
