#' @importFrom glue glue glue_data
NULL

#' @importFrom dplyr vars
#' @export
dplyr::vars

# Alias required for help links in downstream packages
#' @aliases select_helpers
#' @importFrom tidyselect contains
#' @export
tidyselect::contains
#' @importFrom tidyselect ends_with
#' @export
tidyselect::ends_with
#' @importFrom tidyselect everything
#' @export
tidyselect::everything
#' @importFrom tidyselect matches
#' @export
tidyselect::matches
#' @importFrom tidyselect num_range
#' @export
tidyselect::num_range
#' @importFrom tidyselect one_of
#' @export
tidyselect::one_of
#' @importFrom tidyselect starts_with
#' @export
tidyselect::starts_with
#' @importFrom tidyselect last_col
#' @export
tidyselect::last_col

#' Expectation params
#' @keywords internal
#' @param var an unquoted variable name
#' @param vars a list of columns generated by [vars()][dplyr::vars()]
#' @param flt a filter specifying a subset of the dataset to test
#' @param miss a vector of values to be treated as missing. The
#'   [testdat.miss][testdat] option is used by default
#' @param data data frame to test. The [global test data][global-data] is used
#'   by default.
#' @name data-params
NULL
